(cl:in-package #:sicl-posix-low)

(defconstant +eperm+ 1 "Operation not permitted")
(defconstant +enoent+ 2 "No such file or directory")
(defconstant +esrch+ 3 "No such process")
(defconstant +eintr+ 4 "Interrupted system call")
(defconstant +eio+ 5 "I/O error")
(defconstant +enxio+ 6 "No such device or address")
(defconstant +e2big+ 7 "Argument list too long")
(defconstant +enoexec+ 8 "Exec format error")
(defconstant +ebadf+ 9 "Bad file number")
(defconstant +echild+ 10 "No child processes")
(defconstant +eagain+ 11 "Try again")
(defconstant +enomem+ 12 "Out of memory")
(defconstant +eacces+ 13 "Permission denied")
(defconstant +efault+ 14 "Bad address")
(defconstant +enotblk+ 15 "Block device required")
(defconstant +ebusy+ 16 "Device or resource busy")
(defconstant +eexist+ 17 "File exists")
(defconstant +exdev+ 18 "Cross-device link")
(defconstant +enodev+ 19 "No such device")
(defconstant +enotdir+ 20 "Not a directory")
(defconstant +eisdir+ 21 "Is a directory")
(defconstant +einval+ 22 "Invalid argument")
(defconstant +enfile+ 23 "File table overflow")
(defconstant +emfile+ 24 "Too many open files")
(defconstant +enotty+ 25 "Not a typewriter")
(defconstant +etxtbsy+ 26 "Text file busy")
(defconstant +efbig+ 27 "File too large")
(defconstant +enospc+ 28 "No space left on device")
(defconstant +espipe+ 29 "Illegal seek")
(defconstant +erofs+ 30 "Read-only file system")
(defconstant +emlink+ 31 "Too many links")
(defconstant +epipe+ 32 "Broken pipe")
(defconstant +edom+ 33 "Math argument out of domain of func")
(defconstant +erange+ 34 "Math result not representable")
(defconstant +edeadlk+ 35 "Resource deadlock would occur")
(defconstant +enametoolong+ 36 "File name too long")
(defconstant +enolck+ 37 "No record locks available")
(defconstant +enosys+ 38 "Function not implemented")
(defconstant +enotempty+ 39 "Directory not empty")
(defconstant +eloop+ 40 "Too many symbolic links encountered")
(defconstant +enomsg+ 42 "No message of desired type")
(defconstant +eidrm+ 43 "Identifier removed")
(defconstant +echrng+ 44 "Channel number out of range")
(defconstant +el2nsync+ 45 "Level 2 not synchronized")
(defconstant +el3hlt+ 46 "Level 3 halted")
(defconstant +el3rst+ 47 "Level 3 reset")
(defconstant +elnrng+ 48 "Link number out of range")
(defconstant +eunatch+ 49 "Protocol driver not attached")
(defconstant +enocsi+ 50 "No CSI structure available")
(defconstant +el2hlt+ 51 "Level 2 halted")
(defconstant +ebade+ 52 "Invalid exchange")
(defconstant +ebadr+ 53 "Invalid request descriptor")
(defconstant +exfull+ 54 "Exchange full")
(defconstant +enoano+ 55 "No anode")
(defconstant +ebadrqc+ 56 "Invalid request code")
(defconstant +ebadslt+ 57 "Invalid slot")
(defconstant +ebfont+ 59 "Bad font file format")
(defconstant +enostr+ 60 "Device not a stream")
(defconstant +enodata+ 61 "No data available")
(defconstant +etime+ 62 "Timer expired")
(defconstant +enosr+ 63 "Out of streams resources")
(defconstant +enonet+ 64 "Machine is not on the network")
(defconstant +enopkg+ 65 "Package not installed")
(defconstant +eremote+ 66 "Object is remote")
(defconstant +enolink+ 67 "Link has been severed")
(defconstant +eadv+ 68 "Advertise error")
(defconstant +esrmnt+ 69 "Srmount error")
(defconstant +ecomm+ 70 "Communication error on send")
(defconstant +eproto+ 71 "Protocol error")
(defconstant +emultihop+ 72 "Multihop attempted")
(defconstant +edotdot+ 73 "RFS specific error")
(defconstant +ebadmsg+ 74 "Not a data message")
(defconstant +eoverflow+ 75 "Value too large for defined data type")
(defconstant +enotuniq+ 76 "Name not unique on network")
(defconstant +ebadfd+ 77 "File descriptor in bad state")
(defconstant +eremchg+ 78 "Remote address changed")
(defconstant +elibacc+ 79 "Can not access a needed shared library")
(defconstant +elibbad+ 80 "Accessing a corrupted shared library")
(defconstant +elibscn+ 81 ".lib section in a.out corrupted")
(defconstant +elibmax+ 82 "Attempting to link in too many shared libraries")
(defconstant +elibexec+ 83 "Cannot exec a shared library directly")
(defconstant +eilseq+ 84 "Illegal byte sequence")
(defconstant +erestart+ 85 "Interrupted system call should be restarted")
(defconstant +estrpipe+ 86 "Streams pipe error")
(defconstant +eusers+ 87 "Too many users")
(defconstant +enotsock+ 88 "Socket operation on non-socket")
(defconstant +edestaddrreq+ 89 "Destination address required")
(defconstant +emsgsize+ 90 "Message too long")
(defconstant +eprototype+ 91 "Protocol wrong type for socket")
(defconstant +enoprotoopt+ 92 "Protocol not available")
(defconstant +eprotonosupport+ 93 "Protocol not supported")
(defconstant +esocktnosupport+ 94 "Socket type not supported")
(defconstant +eopnotsupp+ 95 "Operation not supported on transport endpoint")
(defconstant +epfnosupport+ 96 "Protocol family not supported")
(defconstant +eafnosupport+ 97 "Address family not supported by protocol")
(defconstant +eaddrinuse+ 98 "Address already in use")
(defconstant +eaddrnotavail+ 99 "Cannot assign requested address")
(defconstant +enetdown+ 100 "Network is down")
(defconstant +enetunreach+ 101 "Network is unreachable")
(defconstant +enetreset+ 102 "Network dropped connection because of reset")
(defconstant +econnaborted+ 103 "Software caused connection abort")
(defconstant +econnreset+ 104 "Connection reset by peer")
(defconstant +enobufs+ 105 "No buffer space available")
(defconstant +eisconn+ 106 "Transport endpoint is already connected")
(defconstant +enotconn+ 107 "Transport endpoint is not connected")
(defconstant +eshutdown+ 108 "Cannot send after transport endpoint shutdown")
(defconstant +etoomanyrefs+ 109 "Too many references: cannot splice")
(defconstant +etimedout+ 110 "Connection timed out")
(defconstant +econnrefused+ 111 "Connection refused")
(defconstant +ehostdown+ 112 "Host is down")
(defconstant +ehostunreach+ 113 "No route to host")
(defconstant +ealready+ 114 "Operation already in progress")
(defconstant +einprogress+ 115 "Operation now in progress")
(defconstant +estale+ 116 "Stale NFS file handle")
(defconstant +euclean+ 117 "Structure needs cleaning")
(defconstant +enotnam+ 118 "Not a XENIX named type file")
(defconstant +enavail+ 119 "No XENIX semaphores available")
(defconstant +eisnam+ 120 "Is a named type file")
(defconstant +eremoteio+ 121 "Remote I/O error")
(defconstant +edquot+ 122 "Quota exceeded")
(defconstant +enomedium+ 123 "No medium found")
(defconstant +emediumtype+ 124 "Wrong medium type")
(defconstant +ecanceled+ 125 "Operation Canceled")
(defconstant +enokey+ 126 "Required key not available")
(defconstant +ekeyexpired+ 127 "Key has expired")
(defconstant +ekeyrevoked+ 128 "Key has been revoked")
(defconstant +ekeyrejected+ 129 "Key was rejected by service")
(defconstant +eownerdead+ 130 "Owner died")
(defconstant +enotrecoverable+ 131 "State not recoverable")
