(cl:in-package #:common-lisp-user)

(defpackage #:sicl-posix-low
  (:use #:common-lisp)
  (:shadow #:read
           #:write)
  (:export #:read
           #:write
           #:+e2big+
           #:+eaccess+
           #:+eaddrinuse+
           #:+eaddrnotavail+
           #:+eafnosupport+
           #:+eagain+
           #:+ealready+
           #:+ebade+
           #:+ebadf+
           #:+ebadfd+
           #:+ebadmsg+
           #:+ebadr+
           #:+ebadrqc+
           #:+ebadslt+
           #:+ebusy+
           #:+ecanceled+
           #:+echild+
           #:+echrng+
           #:+ecomm+
           #:+econnaborted+
           #:+econnrefused+
           #:+econnreset+
           #:+edeadlk+
           #:+edeadlock+
           #:+edestaddrreq+
           #:+edom+
           #:+edquot+
           #:+eexist+
           #:+efault+
           #:+efbig+
           #:+ehostdown+
           #:+ehostunreach+
           #:+eidrm+
           #:+eilseq+
           #:+einprogress+
           #:+eintr+
           #:+einval+
           #:+eio+
           #:+eisconn+
           #:+eisdir+
           #:+eisnam+
           #:+ekeyexpired+
           #:+ekeyrejected+
           #:+ekeyrevoked+
           #:+el2hlt+
           #:+el2nsync+
           #:+el3hlt+
           #:+el3rst+
           #:+elibacc+
           #:+elibbad+
           #:+elibmax+
           #:+elibscn+
           #:+elibexec+
           #:+eloop+
           #:+emediumtype+
           #:+emfile+
           #:+emlink+
           #:+emsgsize+
           #:+emultihop+
           #:+enametoolong+
           #:+enetdown+
           #:+enetreset+
           #:+enetunreach+
           #:+enfile+
           #:+enobufs+
           #:+enodata+
           #:+enodev+
           #:+enoent+
           #:+enoexec+
           #:+enokey+
           #:+enolck+
           #:+enolink+
           #:+enomedium+
           #:+enomem+
           #:+enomsg+
           #:+enonet+
           #:+enopkg+
           #:+enoprotoopt+
           #:+enospc+
           #:+enosr+
           #:+enostr+
           #:+enosys+
           #:+enotblk+
           #:+enotconn+
           #:+enotdir+
           #:+enotempty+
           #:+enotsock+
           #:+enotsup+
           #:+enotty+
           #:+enotuniq+
           #:+enxio+
           #:+eopnotsupp+
           #:+eoverflow+
           #:+eperm+
           #:+epfnosupport+
           #:+epipe+
           #:+eproto+
           #:+eprotonosupport+
           #:+eprototype+
           #:+erange+
           #:+eremchg+
           #:+eremote+
           #:+eremoteio+
           #:+erestart+
           #:+erofs+
           #:+eshutdown+
           #:+espipe+
           #:+esocktnosupport+
           #:+esrch+
           #:+estale+
           #:+estrpipe+
           #:+etime+
           #:+etimedout+
           #:+etxtbsy+
           #:+euclean+
           #:+eunatch+
           #:+eusers+
           #:+ewouldblock+
           #:+exdev+
           #:+exfull+))
