(cl:in-package #:sicl-sequence)

(defmacro with-key-function ((name key) &body body)
  (sicl-utilities:with-gensyms (f)
    (sicl-utilities:once-only (key)
      `(let ((,f (if (null ,key) nil (function-designator-function ,key))))
         (declare (type (or function null) ,f))
         (flet ((,name (x) (if (null ,f) x (funcall ,f x))))
           (declare (inline ,name))
           ,@body)))))
