(cl:in-package #:sicl-sequence)

(defmacro with-key-function ((name key) &body body)
  (sicl-utilities:with-gensyms (f)
    (sicl-utilities:once-only (key)
      `(if (null ,key)
           (flet ((,name (x) x))
             (declare (inline ,name))
             ,@body)
           (let ((,f (function-designator-function ,key)))
             (declare (function ,f))
             (flet ((,name (x)
                      (funcall ,f x)))
               (declare (inline ,name))
               ,@body))))))
