(cl:in-package #:sicl-boot-phase-4)

(defun boot (boot)
  (format *trace-output* "Start of phase 4~%")
  (with-accessors ((e2 sicl-boot:e2)
                   (e3 sicl-boot:e3)
                   (e4 sicl-boot:e4)
                   (e5 sicl-boot:e5))
      boot
    (change-class e4 'environment)
    (import-from-host boot)
    (sicl-boot:enable-class-finalization #'load-fasl e2 e3)
    (finalize-all-classes boot)
    (sicl-boot:enable-defmethod #'load-fasl e3 e4)
    (enable-allocate-instance e3)
    (define-class-of e4)
    (sicl-boot:enable-object-initialization #'load-fasl e3 e4)
    (load-fasl "Conditionals/macros.fasl" e3)
    (sicl-boot:enable-method-combinations #'load-fasl e3 e4)
    (define-stamp e4)
    (define-compile e4)
    (sicl-boot:enable-generic-function-invocation #'load-fasl e3 e4)
    (load-fasl "CLOS/standard-instance-access.fasl" e4)
    (sicl-boot:define-accessor-generic-functions #'load-fasl e3 e4 e5)
    (sicl-boot:enable-class-initialization #'load-fasl e3 e4 e5)
    (sicl-boot:create-mop-classes #'load-fasl e4)))
