(cl:in-package #:sicl-boot-phase-4)

(defun boot (boot)
  (format *trace-output* "Start of phase 4~%")
  (with-accessors ((e2 sicl-boot:e2)
                   (e3 sicl-boot:e3)
                   (e4 sicl-boot:e4)
                   (e5 sicl-boot:e5))
      boot
    (change-class e4 'environment)
    (import-from-host boot)
    (sicl-boot:enable-class-finalization e2 e3)
    (sicl-boot:finalize-all-classes e3)
    (sicl-boot:enable-defmethod e3 e4)
    (sicl-boot:enable-allocate-instance e3)
    (sicl-boot:define-class-of e4)
    (sicl-boot:enable-object-initialization e3 e4)
    (load-fasl "Conditionals/macros.fasl" e3)
    (sicl-boot:enable-method-combinations e3 e4)
    (define-stamp e4)
    (define-compile e4)
    (sicl-boot:enable-generic-function-invocation e3 e4)
    (load-fasl "CLOS/standard-instance-access.fasl" e4)
    (sicl-boot:enable-defgeneric e3 e4 e5)
    (load-fasl "CLOS/invalidate-discriminating-function.fasl" e4)
    (sicl-boot:enable-generic-function-initialization e4)
    (sicl-boot:load-accessor-defgenerics e5)
    (sicl-boot:enable-class-initialization e3 e4 e5)
    (sicl-boot:create-mop-classes e4)
    (load-fasl "CLOS/satiation.fasl" e4)))
