(cl:in-package #:sicl-boot-phase-4)

(defun boot (boot)
  (format *trace-output* "Start of phase 4~%")
  (with-accessors ((e3 sicl-boot:e3)
                   (e4 sicl-boot:e4))
      boot
    (change-class e4 'environment)
    (import-from-host boot)
    (enable-class-finalization boot)
    (finalize-all-classes boot)
    (enable-defmethod boot)
    (enable-allocate-instance e3)
    (enable-object-initialization boot)
    (load-fasl "Conditionals/macros.fasl" e3)
    (enable-method-combinations boot)
    (enable-generic-function-invocation boot)
    (define-accessor-generic-functions boot)
    (enable-class-initialization boot)
    (create-mop-classes boot)))
