(cl:in-package #:sicl-boot-phase-4)

(defun define-compile (e4)
  (setf (sicl-genv:fdefinition 'compile e4)
        (lambda (name &optional definition)
          (assert (null name))
          (assert (not (null definition)))
          (let* ((cst (cst:cst-from-expression definition))
                 (client (make-instance 'sicl-boot:client)))
            (sicl-hir-evaluator:cst-eval client cst e4)))))
