(cl:in-package #:sicl-boot-phase-4)

(defun enable-object-initialization (ea eb)
  (setf (sicl-genv:special-variable 'sicl-clos:+unbound-slot-value+ ea t)
        10000000)
  (load-fasl "CLOS/slot-bound-using-index.fasl" ea)
  (load-fasl "CLOS/slot-value-etc-support.fasl" ea)
  (load-fasl "CLOS/instance-slots-offset-defconstant.fasl" ea)
  (sicl-boot:with-straddled-function-definitions
      ((sicl-clos::shared-initialize-default-using-class)
       eb)
    (load-fasl "CLOS/shared-initialize-support.fasl" ea))
  (load-fasl "CLOS/shared-initialize-defgenerics.fasl" eb)
  (load-fasl "CLOS/shared-initialize-defmethods.fasl" eb)
  (load-fasl "CLOS/initialize-instance-support.fasl" eb)
  (load-fasl "CLOS/initialize-instance-defgenerics.fasl" eb)
  (load-fasl "CLOS/initialize-instance-defmethods.fasl" eb)
  (sicl-boot:define-make-instance ea eb))
