(cl:in-package #:sicl-boot-phase-0)

(defun compile-files (client environment)
  (flet ((cf (name)
           (format *trace-output* "Compiling file ~s~%" name)
           (compile-file client name environment)))
    (cf "CLOS/t-defclass.lisp")
    (cf "CLOS/standard-object-defclass.lisp")
    (cf "CLOS/metaobject-defclass.lisp")
    (cf "CLOS/method-defclass.lisp")
    (cf "CLOS/standard-method-defclass.lisp")
    (cf "CLOS/standard-accessor-method-defclass.lisp")
    (cf "CLOS/standard-reader-method-defclass.lisp")
    (cf "CLOS/standard-writer-method-defclass.lisp")
    (cf "CLOS/slot-definition-defclass.lisp")
    (cf "CLOS/standard-slot-definition-defclass.lisp")
    (cf "CLOS/direct-slot-definition-defclass.lisp")
    (cf "CLOS/effective-slot-definition-defclass.lisp")
    (cf "CLOS/standard-direct-slot-definition-defclass.lisp")
    (cf "CLOS/standard-effective-slot-definition-defclass.lisp")
    (cf "CLOS/method-combination-defclass.lisp")
    (cf "CLOS/specializer-defclass.lisp")
    (cf "CLOS/class-defclass.lisp")
    (cf "CLOS/real-class-defclass.lisp")
    (cf "CLOS/regular-class-defclass.lisp")
    (cf "CLOS/standard-class-defclass.lisp")
    (cf "CLOS/funcallable-standard-class-defclass.lisp")
    (cf "CLOS/built-in-class-defclass.lisp")
    (cf "CLOS/forward-referenced-class-defclass.lisp")
    (cf "CLOS/eql-specializer-defclass.lisp")
    (cf "CLOS/funcallable-standard-object-defclass.lisp")
    (cf "CLOS/generic-function-defclass.lisp")
    (cf "CLOS/standard-generic-function-defclass.lisp")))
