(eval-when (:compile-toplevel :load-toplevel :execute)
  (funcall #'(setf sicl-environment::macro-function)
           #'(lambda (#:g1359 #:g1358)
               (declare (ignore #:g1358))
               (let ((#:g1360 (cdr #:g1359)))
                 (let* ((arguments #:g1360))
                   (declare (ignore))
                   (cond ((null arguments)
			  t)
                         ((null (cdr arguments))
			  (car arguments))
                         (t
                          `(when ,(car arguments)
			     (and ,@(cdr arguments))))))))
           'and))
