(cl:in-package #:sicl-boot-phase-2)

(defun load-mop-defclasses (boot)
  (with-accessors ((e2 sicl-boot:e2))
      boot
    (flet ((ld (relative-pathname)
             (sicl-boot:load-fasl relative-pathname e2)))
      (ld "CLOS/t-defclass.fasl")
      (ld "CLOS/function-defclass.fasl")
      (ld "CLOS/standard-object-defclass.fasl")
      (ld "CLOS/metaobject-defclass.fasl")
      (ld "CLOS/method-defclass.fasl")
      (ld "CLOS/standard-method-defclass.fasl")
      (ld "CLOS/standard-accessor-method-defclass.fasl")
      (ld "CLOS/standard-reader-method-defclass.fasl")
      (ld "CLOS/standard-writer-method-defclass.fasl")
      (ld "CLOS/slot-definition-defclass.fasl")
      (ld "CLOS/standard-slot-definition-defclass.fasl")
      (ld "CLOS/direct-slot-definition-defclass.fasl")
      (ld "CLOS/effective-slot-definition-defclass.fasl")
      (ld "CLOS/standard-direct-slot-definition-defclass.fasl")
      (ld "CLOS/standard-effective-slot-definition-defclass.fasl")
      (ld "CLOS/method-combination-defclass.fasl")
      (ld "CLOS/specializer-defclass.fasl")
      (ld "CLOS/eql-specializer-defclass.fasl")
      (ld "CLOS/class-unique-number-defparameter.fasl")
      (ld "CLOS/class-defclass.fasl")
      (ld "CLOS/forward-referenced-class-defclass.fasl")
      (ld "CLOS/real-class-defclass.fasl")
      (ld "CLOS/regular-class-defclass.fasl")
      (ld "CLOS/standard-class-defclass.fasl")
      (ld "CLOS/funcallable-standard-class-defclass.fasl")
      (ld "CLOS/built-in-class-defclass.fasl")
      (ld "CLOS/funcallable-standard-object-defclass.fasl")
      (ld "CLOS/simple-function-defclass.fasl")
      (ld "CLOS/generic-function-defclass.fasl")
      (ld "CLOS/standard-generic-function-defclass.fasl")
      (ld "Cons/cons-defclass.fasl")
      (ld "Sequence/sequence-defclass.fasl")
      (ld "Cons/list-defclass.fasl")
      (ld "Package-and-symbol/symbol-defclass.fasl")
      (ld "Arithmetic/number-defclass.fasl")
      (ld "Arithmetic/real-defclass.fasl")
      (ld "Arithmetic/rational-defclass.fasl")
      (ld "Arithmetic/integer-defclass.fasl")
      (ld "Arithmetic/fixnum-defclass.fasl"))))
