(cl:in-package #:sicl-printer)

(defmethod print-object ((object cons) stream)
  (format stream "(")
  (format stream "~s" (first object))
  (loop for remaining = (rest object) then (rest remaining)
        while (consp remaining)
        do (format stream " ~s" (first remaining))
        finally (if (null remaining)
                    (format stream ")")
                    (format stream " . ~s)" remaining))))
