(cl:in-package #:sicl-arithmetic)

(defmethod generic-floor ((number fixnum) (divisor fixnum))
  (cond ((zerop divisor)
         (error 'division-by-zero
                :operation 'floor
                :operands (list number divisor)))
        ((zerop number)
         (values 0 0))
        ((minusp number)
         (if (minusp divisor)
             (multiple-value-bind (quotient remainder)
                 (cleavir-primop:fixnum-divide (- number) (- divisor))
               (values quotient (- remainder)))
             (multiple-value-bind (quotient remainder)
                 (cleavir-primop:fixnum-divide (- number) divisor)
               (if (zerop remainder)
                   (values (- quotient) remainder)
                   (values (- (1+ quotient)) (- divisor remainder))))))
        (t
         (if (minusp divisor)
             (multiple-value-bind (quotient remainder)
                 (cleavir-primop:fixnum-divide number (- divisor))
               (if (zerop remainder)
                   (values (- quotient) remainder)
                   (values (- (1+ quotient)) (+ divisor remainder))))
             (multiple-value-bind (quotient remainder)
                 (cleavir-primop:fixnum-divide number divisor)
               (values quotient remainder))))))
