(cl:in-package #:sicl-cons-high)

(define-setf-ith first 1)
(define-setf-ith second 2)
(define-setf-ith third 3)
(define-setf-ith fourth 4)
(define-setf-ith fifth 5)
(define-setf-ith sixth 6)
(define-setf-ith seventh 7)
(define-setf-ith eighth 8)
(define-setf-ith ninth 9)
(define-setf-ith tenth 10)
