(cl:in-package #:sicl-new-boot)

;;; Eclector defines macros that are generated by the backquote
;;; facility.  These macros must exist in the global environment
;;; so that they can be expanded by the compiler.

(defun define-backquote-macros (client environment)
  (setf (clostrum:fdefinition client environment 'eclector.reader::expand)
        (fdefinition 'eclector.reader::expand))
  (setf (clostrum:macro-function client environment 'eclector.reader::quasiquote)
        (macro-function 'eclector.reader::quasiquote)))
