(cl:in-package #:sicl-boot)

(defclass boot ()
  ((%e0 :initarg :e0 :accessor e0)
   (%e1 :initarg :e1 :accessor e1)
   (%e2 :initarg :e2 :accessor e2)
   (%e3 :initarg :e3 :accessor e3)
   (%e4 :initarg :e4 :accessor e4)
   (%e5 :initarg :e5 :accessor e5)))

(defvar *e0*)
(defvar *e1*)
(defvar *e2*)
(defvar *e3*)
(defvar *e4*)
(defvar *e5*)
