(cl:in-package #:sicl-boot)

(defclass boot ()
  ((%r1 :initarg :r1 :reader r1)
   (%r2 :initarg :r2 :reader r2)
   (%r3 :initarg :r3 :reader r3)
   (%r4 :initarg :r4 :reader r4)))

(defmethod initialize-instance :around ((object boot) &key &allow-other-keys)
  (let (r1 r2 r3 r4)
    (message "Creating run-time environment R1~%")
    (setf r1 (make-instance 'sicl-extrinsic-environment:environment))
    (message "Finished creating run-time environment R1~%")
    (message "Creating run-time environment R2~%")
    (setf r2 (make-instance 'sicl-extrinsic-environment:environment))
    (message "Finished creating run-time environment R2~%")
    (message "Creating run-time environment R3~%")
    (setf r3 (make-instance 'sicl-extrinsic-environment:environment))
    (message "Finished creating run-time environment R3~%")
    (setf r4 (make-instance 'sicl-extrinsic-environment:environment))
    (message "Finished creating run-time environment R4~%")
    (call-next-method object :r1 r1 :r2 r2 :r3 r3 :r4 r4)))
