(cl:in-package #:sicl-boot)

(defun create-bridge-class-accessors (boot)
  (let ((c (c2 boot))
	(r (r3 boot)))
  (ld "../CLOS/method-function-defgeneric.lisp" c r)
  (ld "../CLOS/method-generic-function-defgeneric.lisp" c r)
  (ld "../CLOS/method-lambda-list-defgeneric.lisp" c r)
  (ld "../CLOS/method-qualifiers-defgeneric.lisp" c r)
  (ld "../CLOS/method-specializers-defgeneric.lisp" c r)
  (ld "../CLOS/accessor-method-slot-definition-defgeneric.lisp" c r)
  (ld "../CLOS/slot-definition-name-defgeneric.lisp" c r)
  (ld "../CLOS/slot-definition-allocation-defgeneric.lisp" c r)
  (ld "../CLOS/slot-definition-type-defgeneric.lisp" c r)
  (ld "../CLOS/slot-definition-initargs-defgeneric.lisp" c r)
  (ld "../CLOS/slot-definition-initform-defgeneric.lisp" c r)
  (ld "../CLOS/slot-definition-initfunction-defgeneric.lisp" c r)
  (ld "../CLOS/slot-definition-readers-defgeneric.lisp" c r)
  (ld "../CLOS/slot-definition-writers-defgeneric.lisp" c r)
  (ld "../CLOS/slot-definition-location-defgeneric.lisp" c r)
  (ld "../CLOS/class-name-defgeneric.lisp" c r)
  (ld "../CLOS/class-direct-superclasses-defgeneric.lisp" c r)
  (ld "../CLOS/class-direct-subclasses-defgeneric.lisp" c r)
  (ld "../CLOS/setf-class-direct-subclasses-defgeneric.lisp" c r)
  (ld "../CLOS/class-direct-slots-defgeneric.lisp" c r)
  (ld "../CLOS/class-direct-default-initargs-defgeneric.lisp" c r)
  (ld "../CLOS/class-precedence-list-defgeneric.lisp" c r)
  (ld "../CLOS/class-slots-defgeneric.lisp" c r)
  (ld "../CLOS/class-default-initargs-defgeneric.lisp" c r)
  (ld "../CLOS/class-finalized-p-defgeneric.lisp" c r)
  (ld "../CLOS/class-prototype-defgeneric.lisp" c r)))
