(cl:in-package #:sicl-boot)

(defun create-classes (ea)
  (flet ((ld (pathname)
           (load-source-file pathname ea)))
    (ld "CLOS/t-defclass.lisp")
    (ld "CLOS/function-defclass.lisp")
    (ld "CLOS/standard-object-defclass.lisp")
    (ld "Structure/structure-object-defclass.lisp")
    (ld "CLOS/metaobject-defclass.lisp")
    (ld "CLOS/method-defclass.lisp")
    (ld "CLOS/standard-method-defclass.lisp")
    (ld "CLOS/standard-accessor-method-defclass.lisp")
    (ld "CLOS/standard-reader-method-defclass.lisp")
    (ld "CLOS/standard-writer-method-defclass.lisp")
    (ld "CLOS/slot-definition-defclass.lisp")
    (ld "CLOS/standard-slot-definition-defclass.lisp")
    (ld "CLOS/direct-slot-definition-defclass.lisp")
    (ld "CLOS/effective-slot-definition-defclass.lisp")
    (ld "CLOS/standard-direct-slot-definition-defclass.lisp")
    (ld "CLOS/standard-effective-slot-definition-defclass.lisp")
    (ld "CLOS/method-combination-defclass.lisp")
    (ld "CLOS/specializer-defclass.lisp")
    (ld "CLOS/eql-specializer-defclass.lisp")
    (ld "CLOS/class-unique-number-defparameter.lisp")
    (ld "CLOS/class-defclass.lisp")
    (ld "CLOS/forward-referenced-class-defclass.lisp")
    (ld "CLOS/real-class-defclass.lisp")
    (ld "CLOS/regular-class-defclass.lisp")
    (ld "CLOS/standard-class-defclass.lisp")
    (ld "CLOS/funcallable-standard-class-defclass.lisp")
    (ld "Structure/structure-class-defclass.lisp")
    (ld "Conditions/condition-class-defclass.lisp")
    (ld "CLOS/built-in-class-defclass.lisp")
    (ld "CLOS/funcallable-standard-object-defclass.lisp")
    (ld "CLOS/simple-function-defclass.lisp")
    (ld "CLOS/generic-function-defclass.lisp")
    (ld "CLOS/standard-generic-function-defclass.lisp")
    (ld "Sequence/sequence-defclass.lisp")
    (ensure-asdf-system '#:sicl-array-load-time ea)
    (ld "String/string-defclass.lisp")
    (ld "Symbol/symbol-defclass.lisp")
    (ld "Cons/list-defclass.lisp")
    (ld "Cons/cons-defclass.lisp")
    (ld "Cons/null-defclass.lisp")
    (ld "Package/package-defclass.lisp")
    (ensure-asdf-system '#:sicl-arithmetic-load-time ea)
    (ld "Character/character-defclass.lisp")
    (ld "Compiler/Code-object/code-object-defclass.lisp")
    (ld "Random/random-state-defclass.lisp")
    (ld "Boot/host-classes.lisp")))
