(cl:in-package #:sicl-boot)

(defun create-classes (ea)
  (flet ((ld (pathname)
           (load-source-file pathname ea)))
    (ensure-asdf-system '#:sicl-clos-load-time ea)
    (ld "Structure/structure-object-defclass.lisp")
    (ld "Structure/structure-class-defclass.lisp")
    (ld "Conditions/condition-class-defclass.lisp")
    (ld "Sequence/sequence-defclass.lisp")
    (ensure-asdf-system '#:sicl-array-load-time ea)
    (ld "String/string-defclass.lisp")
    (ld "Symbol/symbol-defclass.lisp")
    (ensure-asdf-system '#:sicl-cons-load-time ea)
    (ld "Package/package-defclass.lisp")
    (ensure-asdf-system '#:sicl-arithmetic-load-time ea)
    (ld "Character/character-defclass.lisp")
    (ld "Random/random-state-defclass.lisp")
    (ld "Boot/host-classes.lisp")))
