(cl:in-package #:sicl-boot)

(defun enable-method-combinations (load-fasl-function ea eb)
  (flet ((load-fasl (path environment)
           (funcall load-fasl-function path environment)))
    (load-fasl "Method-combination/accessor-defgenerics.fasl" eb)
    (load-fasl "Method-combination/make-method-combination-defun.fasl" eb)
    (load-fasl "Method-combination/find-method-combination.fasl" eb)
    (load-fasl "Method-combination/method-combination-template-defclass.fasl" ea)
    (load-fasl "CLOS/standard-method-combination.fasl" eb)
    (load-fasl "CLOS/find-method-combination-defgenerics.fasl" eb)
    (load-fasl "CLOS/find-method-combination-defmethods.fasl" eb)))
