(cl:in-package #:sicl-boot)

(defun enable-object-initialization (ea eb)
  (setf (sicl-genv:special-variable 'sicl-clos:+unbound-slot-value+ ea t)
        10000000)
  (load-source "CLOS/slot-bound-using-index.lisp" ea)
  (load-source "CLOS/slot-value-etc-support.lisp" ea)
  (load-source "CLOS/slot-value-etc-defgenerics.lisp" ea)
  (load-source "CLOS/slot-value-etc-defmethods.lisp" ea)
  (load-source "CLOS/instance-slots-offset-defconstant.lisp" ea)
  (with-straddled-function-definitions
      ((sicl-clos::shared-initialize-default-using-class)
       eb)
    (load-source "CLOS/shared-initialize-support.lisp" ea))
  (load-source "CLOS/shared-initialize-defgenerics.lisp" eb)
  (load-source "CLOS/shared-initialize-defmethods.lisp" eb)
  (load-source "CLOS/initialize-instance-support.lisp" eb)
  (load-source "CLOS/initialize-instance-defgenerics.lisp" eb)
  (load-source "CLOS/initialize-instance-defmethods.lisp" eb)
  (define-make-instance ea eb))
