(cl:in-package #:sicl-boot)

(defun enable-method-combinations (ea eb)
  (load-source "Method-combination/accessor-defgenerics.lisp" eb)
  (load-source "Method-combination/make-method-combination-defun.lisp" eb)
  (load-source "Method-combination/find-method-combination.lisp" eb)
  (load-source "Method-combination/method-combination-template-defclass.lisp" ea)
  (load-source "CLOS/standard-method-combination.lisp" eb)
  (load-source "CLOS/find-method-combination-defgenerics.lisp" eb)
  (load-source "CLOS/find-method-combination-defmethods.lisp" eb))
