(cl:in-package #:sicl-boot-phase-6)

(defun enable-object-initialization (boot)
  (with-accessors ((e5 sicl-boot:e5)
                   (e6 sicl-boot:e6))
      boot
    (setf (sicl-genv:special-variable 'sicl-clos:+unbound-slot-value+ e5 t)
          10000000)
    (load-fasl "CLOS/slot-bound-using-index.fasl" e5)
    (load-fasl "CLOS/standard-instance-access.fasl" e5)
    (load-fasl "CLOS/slot-value-etc-support.fasl" e5)
    (load-fasl "CLOS/instance-slots-offset-defconstant.fasl" e5)
    (sicl-boot:with-straddled-function-definitions
        ((sicl-clos::shared-initialize-default-using-class)
         e6)
      (load-fasl "CLOS/shared-initialize-support.fasl" e5))
    (untrace)
    (load-fasl "CLOS/shared-initialize-defgenerics.fasl" e6)
    (load-fasl "CLOS/shared-initialize-defmethods.fasl" e6)
    (load-fasl "CLOS/initialize-instance-support.fasl" e6)
    (load-fasl "CLOS/initialize-instance-defgenerics.fasl" e6)
    (load-fasl "CLOS/initialize-instance-defmethods.fasl" e6)
    (sicl-boot:define-make-instance e5 e6)))
