(cl:in-package #:sicl-sequence)

(defparameter *special-array-information*
  '(((simple-array bit) . sbit)
    ((array bit) . bit)
    ((simple-array character) . schar)
    ((array character) . char)
    ((simple-array (unsigned-byte 8)) . aref)
    ((array (unsigned-byte 8)) . aref)
    ((simple-array (signed-byte 8)) . aref)
    ((array (signed-byte 8)) . aref)
    ((simple-array (unsigned-byte 16)) . aref)
    ((array (unsigned-byte 16)) . aref)
    ((simple-array (signed-byte 16)) . aref)
    ((array (signed-byte 16)) . aref)
    ((simple-array (unsigned-byte 32)) . aref)
    ((array (unsigned-byte 32)) . aref)
    ((simple-array (signed-byte 32)) . aref)
    ((array (signed-byte 32)) . aref)
    ((simple-array (unsigned-byte 64)) . aref)
    ((array (unsigned-byte 64)) . aref)
    ((simple-array (signed-byte 64)) . aref)
    ((array (signed-byte 64)) . aref)
    ((simple-array short-float) . aref)
    ((array short-float) . aref)
    ((simple-array single-float) . aref)
    ((array single-float) . aref)
    ((simple-array double-float) . aref)
    ((array double-float) . aref)
    ((simple-array long-float) . aref)
    ((array long-float) . aref)
    ((simple-array (complex short-float)) . aref)
    ((array (complex short-float)) . aref)
    ((simple-array (complex single-float)) . aref)
    ((array (complex single-float)) . aref)
    ((simple-array (complex double-float)) . aref)
    ((array (complex double-float)) . aref)
    ((simple-array (complex long-float)) . aref)
    ((array (complex long-float)) . aref)))
