(in-package #:common-lisp-user)

(defpackage #:sicl-additional-conditions
  (:use #:common-lisp #:sicl-additional-types #:sicl-internationalization)
  (:export
   #:signaler-mixin
   #:sicl-condition
   #:sicl-warning
   #:sicl-style-warning
   #:sicl-error
   #:sicl-type-error
   #:sicl-cell-error
   #:both-test-and-test-not-given
   #:at-least-one-list-required
   #:at-least-one-argument-required
   #:lists-must-have-the-same-length
   #:warn-both-test-and-test-not-given
   #:sicl-program-error
   #:sicl-program-warning
   #:sicl-program-style-warning
   #:form-must-be-proper-list
   #:block-tag-must-be-symbol
   #:body-must-be-proper-list
   #:multiple-documentation-strings-in-body
   #:documentation-string-not-allowed-in-body
   #:declarations-not-allowed-in-body
   #:declaration-follows-form-in-body
   #:form-too-short
   #:form-too-long
   #:unknown-eval-when-situation
   #:go-tag-must-be-symbol-or-integer
   #:setq-must-have-even-number-arguments
   #:setq-variable-must-be-symbol
   #:tagbody-element-must-be-symbol-integer-or-compound-form
   #:lambda-list-must-not-be-circular
   #:lambda-list-must-be-proper-list
   #:lambda-list-keyword-not-allowed
   #:lambda-list-keyword-not-allowed-in-dotted-lambda-list
   #:multiple-occurrences-of-lambda-list-keyword
   #:incorrect-keyword-order
   #:both-rest-and-body-occur-in-lambda-list
   #:whole-must-appear-first
   #:whole-must-be-followed-by-variable
   #:environment-must-be-followed-by-variable
   #:environment-can-appear-at-most-once
   #:empty-body
   #:numeric-catch-tag
   #:deprecated-eval-when-situation
   #:load-time-value-read-only-p-not-evaluated
   #:suspect-lambda-list-keyword
   #:sicl-unbound-variable
   #:sicl-unbound-function))
