(in-package #:common-lisp-user)

(defpackage #:sicl-additional-conditions
  (:use #:common-lisp #:sicl-additional-types)
  (:export
   #:sicl-condition
   #:sicl-warning
   #:sicl-style-warning
   #:sicl-error
   #:sicl-type-error
   #:sicl-cell-error
   #:both-test-and-test-not-given
   #:at-least-one-list-required
   #:at-least-one-argument-required
   #:lists-must-have-the-same-length
   #:warn-both-test-and-test-not-given
   #:list-as-sequence-must-be-proper
   #:invalid-bounding-indexes
   #:invalid-start-index
   #:invalid-end-index
   #:sicl-program-error
   #:sicl-program-warning
   #:sicl-program-style-warning
   #:form-must-be-proper-list
   #:block-tag-must-be-symbol
   #:body-must-be-proper-list
   #:multiple-documentation-strings-in-body
   #:documentation-string-not-allowed-in-body
   #:declarations-not-allowed-in-body
   #:declaration-follows-form-in-body
   #:form-too-short
   #:form-too-long
   #:unknown-eval-when-situation
   #:go-tag-must-be-symbol-or-integer
   #:setq-must-have-even-number-arguments
   #:setq-variable-must-be-symbol
   #:tagbody-element-must-be-symbol-integer-or-compound-form
   #:lambda-list-must-be-list
   #:lambda-list-must-not-be-circular
   #:lambda-list-must-be-proper-list
   #:lambda-list-keyword-not-allowed
   #:lambda-list-keyword-not-allowed-in-dotted-lambda-list
   #:multiple-occurrences-of-lambda-list-keyword
   #:incorrect-keyword-order
   #:both-rest-and-body-occur-in-lambda-list
   #:atomic-lambda-list-tail-must-be-variable
   #:rest/body-must-be-followed-by-variable
   #:whole-must-be-followed-by-variable
   #:whole-must-appear-first
   #:whole-must-be-followed-by-variable
   #:environment-must-be-followed-by-variable
   #:environment-can-appear-at-most-once
   #:empty-body
   #:numeric-catch-tag
   #:deprecated-eval-when-situation
   #:load-time-value-read-only-p-not-evaluated
   #:suspect-lambda-list-keyword
   #:malformed-specialized-required
   #:malformed-ordinary-optional
   #:malformed-defgeneric-optional
   #:malformed-destructuring-optional
   #:malformed-ordinary-key
   #:malformed-defgeneric-key
   #:malformed-destructuring-key
   #:malformed-destructuring-tree
   #:malformed-aux
   #:malformed-lambda-list-pattern
   #:required-must-be-variable
   #:too-few-arguments
   #:too-many-arguments
   #:unrecognized-keyword-argument
   #:invalid-keyword-argument
   #:odd-number-of-keyword-arguments
   #:sicl-unbound-variable
   #:sicl-unbound-function
   #:no-such-class-name
   #:must-be-class-or-nil
   #:superclass-list-must-be-proper-list
   #:class-name-must-be-non-nil-symbol
   #:malformed-slots-list
   #:malformed-slot-spec
   #:illegal-slot-name
   #:slot-options-must-be-even
   #:slot-option-name-must-be-symbol
   #:multiple-initform-options-not-permitted
   #:multiple-documentation-options-not-permitted
   #:multiple-allocation-options-not-permitted
   #:multiple-type-options-not-permitted
   #:slot-documentation-option-must-be-string
   #:class-option-must-be-non-empty-list
   #:class-option-name-must-be-symbol
   #:duplicate-class-option-not-allowed
   #:malformed-documentation-option
   #:malformed-metaclass-option
   #:malformed-default-initargs-option
   #:default-initargs-option-once
   #:documentation-option-once
   #:metaclass-option-once
   #:unknown-class-option)
  (:shadow #:sequence))
