(cl:in-package #:sicl-new-boot)

(defun boot ()
  (unless (null (find-package '#:parcl))
    (rename-package '#:parcl '#:sicl-new-boot-parcl-extrinsic))
  (setf (symbol-value
         (find-symbol "*CLIENT*" '#:sicl-new-boot-parcl-extrinsic))
        (make-instance 'client))
  (let* ((boot (make-instance 'boot))
         (*boot* boot)
         (client (make-instance 'client)))
    (create-common-lisp-package client)
    (loop for name in '("COMMON-LISP-USER" "KEYWORD")
          do (setf (gethash name (packages boot))
                   (find-package name)))
    (when *use-maclina-p*
      (let ((maclina.machine:*client* client))
        (maclina.vm-cross:initialize-vm 20000)))
    (sicl-new-boot-phase-1:boot boot)
    (sicl-new-boot-phase-2:boot boot)
    (sicl-new-boot-phase-3:boot boot)
    (sicl-new-boot-phase-4:boot boot)
    (defparameter *b* boot)))
