(cl:in-package #:common-lisp-user)

(asdf:defsystem :sicl-boot-phase1
  :depends-on (:sicl-code-utilities
	       :sicl-additional-conditions)
  :serial t
  :components
  ((:file "packages")
   (:file "rename-package-1")
   (:file "define-built-in-class")
   (:file "defclass")
   (:file "mop-class-hierarchy")
   (:file "define-variables")
   (:file "classp")
   (:file "specializerp")
   (:file "reader-writer-method-class-support")
   (:file "reader-writer-method-class-defgenerics")
   (:file "reader-writer-method-class-defmethods")
   (:file "add-accessor-method")
   (:file "slot-definition-class-support")
   (:file "slot-definition-class-defgenerics")
   (:file "slot-definition-class-defmethods")
   (:file "validate-superclass")
   (:file "class-initialization-support")
   (:file "class-initialization-defmethods")
   (:file "compute-applicable-methods-support")
   (:file "compute-applicable-methods-defgenerics")
   (:file "compute-applicable-methods-defmethods")
   (:file "compute-effective-method-support")
   (:file "compute-effective-method-support-a")
   (:file "method-combination-compute-effective-method-support")
   (:file "method-combination-compute-effective-method-defgenerics")
   (:file "method-combination-compute-effective-method-defmethods")
   (:file "compute-effective-method-defgenerics")
   (:file "compute-effective-method-defmethods")
   (:file "list-utilities")
   (:file "discriminating-automaton")
   (:file "discriminating-tagbody")
   (:file "heap-instance")
   (:file "standard-instance-access")
   (:file "compute-discriminating-function-support")
   (:file "compute-discriminating-function-support-a")
   (:file "compute-discriminating-function-defgenerics")
   (:file "compute-discriminating-function-defmethods")
   ;; Although we do not use the dependent maintenance facility, we
   ;; define the specified functions as ordinary functions that do
   ;; nothing, so that we can safely call them from other code.
   (:file "dependent-maintenance-support")
   (:file "dependent-maintenance-defuns")
   (:file "set-funcallable-instance-function")
   (:file "generic-function-initialization-support")
   (:file "generic-function-initialization-defmethods")
   (:file "direct-slot-definition-p")
   (:file "method-initialization-support")
   (:file "method-initialization-defmethods")
   (:file "print-object")
   (:file "rename-package-2")))
