(cl:in-package #:sicl-data-and-control-flow)

(symbol-macrolet ((client sicl-client:*client*))
  (let* ((environment (env:global-environment))
         (setf-fdefinition (fdefinition '(setf env:fdefinition)))
         (setf-macro-function (fdefinition '(setf env:macro-function))))
    (defun fmakunbound (function-name)
      (funcall setf-fdefinition nil client environment function-name)
      (funcall setf-macro-function nil client environment function-name)
      function-name)))
