(cl:in-package #:sicl-data-and-control-flow)

(let* ((environment (env:global-environment))
       (client (env:client environment))
       (setf-fdefinition (fdefinition '(setf env:fdefinition)))
       (setf-macro-function (fdefinition '(setf env:macro-function))))
  (defun fmakunbound (function-name)
    (funcall setf-fdefinition nil client environment function-name)
    (funcall setf-macro-function nil client environment function-name)
    function-name))
