(cl:in-package #:sicl-code-generation)

(defun linearize-function (enter-instruction)
  (let ((result '())
        (worklist (list enter-instruction))
        (visited (make-hash-table :test #'eq)))
    (loop until (null worklist)
          do (let ((instruction (pop worklist)))
               (unless (gethash instruction visited)
                 (setf (gethash instruction visited) t)
                 (push instruction result)
                 (loop for successor in (reverse (cleavir-ir:successors instruction))
                       do (push successor worklist)))))
    (reverse result)))
