(cl:in-package #:sicl-boot-phase-8)

(defun load-data-and-control-flow-code (e5)
  (load-source "Data-and-control-flow/eq-defun.lisp" e5)
  (load-source "Data-and-control-flow/defun-defmacro.lisp" e5)
  (load-source "Data-and-control-flow/fdefinition-defun.lisp" e5)
  (load-source "Data-and-control-flow/setf-fdefinition-defun.lisp" e5)
  (load-source "Data-and-control-flow/fboundp-defun.lisp" e5)
  (load-source "Data-and-control-flow/fmakunbound-defun.lisp" e5)
  (load-source "Data-and-control-flow/functionp-defgeneric.lisp" e5)
  (load-source "Data-and-control-flow/functionp-defmethods.lisp" e5)
  (load-source "Data-and-control-flow/defconstant-defmacro.lisp" e5)
  (load-source "Data-and-control-flow/defparameter-defmacro.lisp" e5)
  (load-source "Data-and-control-flow/defvar-defmacro.lisp" e5)
  (load-source "Data-and-control-flow/return-defmacro.lisp" e5)
  (load-source "Data-and-control-flow/psetf-support.lisp" e5)
  (load-source "Data-and-control-flow/psetf-defmacro.lisp" e5)
  (load-source "Data-and-control-flow/psetq-defmacro.lisp" e5)
  (load-source "Data-and-control-flow/destructuring-bind-defmacro.lisp" e5)
  (load-source "Data-and-control-flow/rotatef-defmacro.lisp" e5)
  (load-source "Data-and-control-flow/shiftf-support.lisp" e5)
  (load-source "Data-and-control-flow/shiftf-defmacro.lisp" e5)
  (load-source "Data-and-control-flow/multiple-value-list-defmacro.lisp" e5)
  (load-source "Data-and-control-flow/get-setf-expansion-defun.lisp" e5))
