(cl:in-package #:sicl-cons)

(defun |intersection key=identity test=eql| (name list1 list2)
  (let ((result '()))
    (with-proper-list-elements (element1 list1 name)
      (when (|member test=eql key=identity| name element1 list2)
        (push element1 result)))
    result))

(defun |intersection key=identity test=eq| (name list1 list2)
  (let ((result '()))
    (with-proper-list-elements (element1 list1 name)
      (when (|member test=eq key=identity| name element1 list2)
        (push element1 result)))
    result))

(defun |intersection key=other test=eql| (name list1 list2 key)
  (let ((result '()))
    (with-proper-list-elements (element1 list1 name)
      (when (|member test=eql key=other| name (funcall key element1) list2 key)
        (push element1 result)))
    result))

(defun |intersection key=other test=eq| (name list1 list2 key)
  (let ((result '()))
    (with-proper-list-elements (element1 list1 name)
      (when (|member test=eq key=other| name (funcall key element1) list2 key)
        (push element1 result)))
    result))

(defun |intersection key=identity test=other| (name list1 list2 test)
  (let ((result '()))
    (with-proper-list-elements (element1 list1 name)
      (when (|member test=other key=identity| name element1 list2 test)
        (push element1 result)))
    result))

(defun |intersection key=other test=other| (name list1 list2 key test)
  (let ((result '()))
    (with-proper-list-elements (element1 list1 name)
      (when (|member test=other key=other| name (funcall key element1) list2 test key)
        (push element1 result)))
    result))

(defun |intersection key=identity test-not=other| (name list1 list2 test-not)
  (let ((result '()))
    (with-proper-list-elements (element1 list1 name)
      (when (|member test-not=other key=identity| name element1 list2 test-not)
        (push element1 result)))
    result))

(defun |intersection key=other test-not=other| (name list1 list2 key test-not)
  (let ((result '()))
    (with-proper-list-elements (element1 list1 name)
      (when (|member test-not=other key=other| name (funcall key element1) list2 test-not key)
        (push element1 result)))
    result))

(defun |intersection key=identity test=eq hash| (name list1 list2)
  (let ((table (make-hash-table :test #'eq))
        (result '()))
    (with-proper-list-elements (element list2 name)
      (setf (gethash element table) t))
    (with-proper-list-elements (element list1 name)
      (when (gethash element table)
        (push element result)))
    result))

(defun |intersection key=identity test=eql hash| (name list1 list2)
  (let ((table (make-hash-table :test #'eql))
        (result '()))
    (with-proper-list-elements (element list2 name)
      (setf (gethash element table) t))
    (with-proper-list-elements (element list1 name)
      (when (gethash element table)
        (push element result)))
    result))

(defun |intersection key=identity test=equal hash| (name list1 list2)
  (let ((table (make-hash-table :test #'equal))
        (result '()))
    (with-proper-list-elements (element list2 name)
      (setf (gethash element table) t))
    (with-proper-list-elements (element list1 name)
      (when (gethash element table)
        (push element result)))
    result))

(defun |intersection key=identity test=equalp hash| (name list1 list2)
  (let ((table (make-hash-table :test #'equalp))
        (result '()))
    (with-proper-list-elements (element list2 name)
      (setf (gethash element table) t))
    (with-proper-list-elements (element list1 name)
      (when (gethash element table)
        (push element result)))
    result))

(defun |intersection key=other test=eq hash| (name list1 list2 key)
  (let ((table (make-hash-table :test #'eq))
        (result '()))
    (with-proper-list-elements (element list2 name)
      (setf (gethash (funcall key element) table) t))
    (with-proper-list-elements (element list1 name)
      (when (gethash (funcall key element) table)
        (push element result)))
    result))

(defun |intersection key=other test=eql hash| (name list1 list2 key)
  (let ((table (make-hash-table :test #'eql))
        (result '()))
    (with-proper-list-elements (element list2 name)
      (setf (gethash (funcall key element) table) t))
    (with-proper-list-elements (element list1 name)
      (when (gethash (funcall key element) table)
        (push element result)))
    result))

(defun |intersection key=other test=equal hash| (name list1 list2 key)
  (let ((table (make-hash-table :test #'equal))
        (result '()))
    (with-proper-list-elements (element list2 name)
      (setf (gethash (funcall key element) table) t))
    (with-proper-list-elements (element list1 name)
      (when (gethash (funcall key element) table)
        (push element result)))
    result))
         
(defun |intersection key=other test=equalp hash| (name list1 list2 key)
  (let ((table (make-hash-table :test #'equalp))
        (result '()))
    (with-proper-list-elements (element list2 name)
      (setf (gethash (funcall key element) table) t))
    (with-proper-list-elements (element list1 name)
      (when (gethash (funcall key element) table)
        (push element result)))
    result))

(defun intersection (list1 list2
                     &key key (test nil test-given) (test-not nil test-not-given))
  (when (and test-given test-not-given)
    (error 'both-test-and-test-not-given :name 'intersection))
  (let ((use-hash (> (* (length list1) (length list2)) 1000)))
    (if key
        (if test-given
            (cond ((or (eq test #'eq) (eq test 'eq))
                   (if use-hash
                       (|intersection key=other test=eq hash| 'intersection list1 list2 key)
                       (|intersection key=other test=eq| 'intersection list1 list2 key)))
                  ((or (eq test #'eql) (eq test 'eql))
                   (if use-hash
                       (|intersection key=other test=eql hash| 'intersection list1 list2 key)
                       (|intersection key=other test=eql| 'intersection list1 list2 key)))
                  ((or (eq test #'equal) (eq test 'equal))
                   (if use-hash
                       (|intersection key=other test=equal hash| 'intersection list1 list2 key)
                       (|intersection key=other test=other| 'intersection list1 list2 key #'equal)))
                  ((or (eq test #'equalp) (eq test 'equalp))
                   (if use-hash
                       (|intersection key=other test=equalp hash| 'intersection list1 list2 key)
                       (|intersection key=other test=other| 'intersection list1 list2 key #'equalp)))
                  (t
                   (|intersection key=other test=other| 'intersection list1 list2 key test)))
            (if test-not-given
                (|intersection key=other test-not=other| 'intersection list1 list2 key test-not)
                (if use-hash
                    (|intersection key=other test=eql hash| 'intersection list1 list2 key)
                    (|intersection key=other test=eql| 'intersection list1 list2 key))))
        (if test-given
            (cond ((or (eq test #'eq) (eq test 'eq))
                   (if use-hash
                       (|intersection key=identity test=eq hash| 'intersection list1 list2)
                       (|intersection key=identity test=eq| 'intersection list1 list2)))
                  ((or (eq test #'eql) (eq test 'eql))
                   (if use-hash
                       (|intersection key=identity test=eql hash| 'intersection list1 list2)
                       (|intersection key=identity test=eql| 'intersection list1 list2)))
                  ((or (eq test #'equal) (eq test 'equal))
                   (if use-hash
                       (|intersection key=identity test=equal hash| 'intersection list1 list2)
                       (|intersection key=identity test=other| 'intersection list1 list2 #'equal)))
                  ((or (eq test #'equalp) (eq test 'equalp))
                   (if use-hash
                       (|intersection key=identity test=equalp hash| 'intersection list1 list2)
                       (|intersection key=identity test=other| 'intersection list1 list2 #'equalp)))
                  (t
                   (|intersection key=identity test=other| 'intersection list1 list2 test)))
            (if test-not-given
                (|intersection key=identity test-not=other| 'intersection list1 list2 test-not)
                (if use-hash
                    (|intersection key=identity test=eql hash| 'intersection list1 list2)
                    (|intersection key=identity test=eql| 'intersection list1 list2)))))))
