(cl:in-package #:sicl-extrinsic-environment)

;;; The SICL reader defines macros that are generated by the backquote
;;; facility.  These macros must exist in the SICL global environment
;;; so that they can be expanded by the compiler.

(defun define-backquote-macros (environment)
  (setf (sicl-env:fdefinition 'sicl-reader::expand environment)
	(fdefinition 'sicl-reader::transform))
  (setf (sicl-env:macro-function 'sicl-reader::quasiquote environment)
	(macro-function 'sicl-reader::quasiquote)))
