(cl:in-package #:sicl-extrinsic-environment)

;;; Fill the target environment with all available packages in the host.
(defun import-host-packages (environment)
  (setf (sicl-env:packages environment)
	(list-all-packages))
  (do-all-symbols (symbol)
    (when (and (fboundp symbol)
	       (not (special-operator-p symbol))
	       (null (macro-function symbol)))
      (setf (sicl-global-environment:fdefinition symbol environment)
	    (fdefinition symbol)))
    (when (fboundp `(setf ,symbol))
      (setf (sicl-global-environment:fdefinition `(setf ,symbol) environment)
	    (fdefinition `(setf ,symbol))))))
