(cl:in-package #:sicl-boot-phase-3)

(defun enable-generic-function-initialization (ea)
  (load-fasl "CLOS/generic-function-initialization-support.fasl" ea)
  (load-fasl "CLOS/generic-function-initialization-defmethods.fasl" ea))

(defun load-accessor-defgenerics (ea)
  (load-fasl "CLOS/specializer-direct-generic-functions-defgeneric.fasl" ea)
  (load-fasl "CLOS/setf-specializer-direct-generic-functions-defgeneric.fasl" ea)
  (load-fasl "CLOS/specializer-direct-methods-defgeneric.fasl" ea)
  (load-fasl "CLOS/setf-specializer-direct-methods-defgeneric.fasl" ea)
  (load-fasl "CLOS/eql-specializer-object-defgeneric.fasl" ea)
  (load-fasl "CLOS/unique-number-defgeneric.fasl" ea)
  (load-fasl "CLOS/class-name-defgeneric.fasl" ea)
  (load-fasl "CLOS/class-direct-subclasses-defgeneric.fasl" ea)
  (load-fasl "CLOS/setf-class-direct-subclasses-defgeneric.fasl" ea)
  (load-fasl "CLOS/class-direct-default-initargs-defgeneric.fasl" ea)
  (load-fasl "CLOS/documentation-defgeneric.fasl" ea)
  (load-fasl "CLOS/setf-documentation-defgeneric.fasl" ea)
  (load-fasl "CLOS/class-finalized-p-defgeneric.fasl" ea)
  (load-fasl "CLOS/setf-class-finalized-p-defgeneric.fasl" ea)
  (load-fasl "CLOS/class-precedence-list-defgeneric.fasl" ea)
  (load-fasl "CLOS/precedence-list-defgeneric.fasl" ea)
  (load-fasl "CLOS/setf-precedence-list-defgeneric.fasl" ea)
  (load-fasl "CLOS/instance-size-defgeneric.fasl" ea)
  (load-fasl "CLOS/setf-instance-size-defgeneric.fasl" ea)
  (load-fasl "CLOS/class-direct-slots-defgeneric.fasl" ea)
  (load-fasl "CLOS/class-direct-superclasses-defgeneric.fasl" ea)
  (load-fasl "CLOS/class-default-initargs-defgeneric.fasl" ea)
  (load-fasl "CLOS/setf-class-default-initargs-defgeneric.fasl" ea)
  (load-fasl "CLOS/class-slots-defgeneric.fasl" ea)
  (load-fasl "CLOS/setf-class-slots-defgeneric.fasl" ea)
  (load-fasl "CLOS/class-prototype-defgeneric.fasl" ea)
  (load-fasl "CLOS/setf-class-prototype-defgeneric.fasl" ea)
  (load-fasl "CLOS/entry-point-defgenerics.fasl" ea)
  (load-fasl "CLOS/environment-defgenerics.fasl" ea)
  (load-fasl "CLOS/dependents-defgeneric.fasl" ea)
  (load-fasl "CLOS/setf-dependents-defgeneric.fasl" ea)
  (load-fasl "CLOS/generic-function-name-defgeneric.fasl" ea)
  (load-fasl "CLOS/generic-function-lambda-list-defgeneric.fasl" ea)
  (load-fasl "CLOS/generic-function-argument-precedence-order-defgeneric.fasl" ea)
  (load-fasl "CLOS/generic-function-declarations-defgeneric.fasl" ea)
  (load-fasl "CLOS/generic-function-method-class-defgeneric.fasl" ea)
  (load-fasl "CLOS/generic-function-method-combination-defgeneric.fasl" ea)
  (load-fasl "CLOS/generic-function-methods-defgeneric.fasl" ea)
  (load-fasl "CLOS/setf-generic-function-methods-defgeneric.fasl" ea)
  (load-fasl "CLOS/initial-methods-defgeneric.fasl" ea)
  (load-fasl "CLOS/setf-initial-methods-defgeneric.fasl" ea)
  (load-fasl "CLOS/call-history-defgeneric.fasl" ea)
  (load-fasl "CLOS/setf-call-history-defgeneric.fasl" ea)
  (load-fasl "CLOS/specializer-profile-defgeneric.fasl" ea)
  (load-fasl "CLOS/setf-specializer-profile-defgeneric.fasl" ea)
  (load-fasl "CLOS/method-function-defgeneric.fasl" ea)
  (load-fasl "CLOS/method-generic-function-defgeneric.fasl" ea)
  (load-fasl "CLOS/setf-method-generic-function-defgeneric.fasl" ea)
  (load-fasl "CLOS/method-lambda-list-defgeneric.fasl" ea)
  (load-fasl "CLOS/method-specializers-defgeneric.fasl" ea)
  (load-fasl "CLOS/method-qualifiers-defgeneric.fasl" ea)
  (load-fasl "CLOS/accessor-method-slot-definition-defgeneric.fasl" ea)
  (load-fasl "CLOS/setf-accessor-method-slot-definition-defgeneric.fasl" ea)
  (load-fasl "CLOS/slot-definition-name-defgeneric.fasl" ea)
  (load-fasl "CLOS/slot-definition-allocation-defgeneric.fasl" ea)
  (load-fasl "CLOS/slot-definition-type-defgeneric.fasl" ea)
  (load-fasl "CLOS/slot-definition-initargs-defgeneric.fasl" ea)
  (load-fasl "CLOS/slot-definition-initform-defgeneric.fasl" ea)
  (load-fasl "CLOS/slot-definition-initfunction-defgeneric.fasl" ea)
  (load-fasl "CLOS/slot-definition-storage-defgeneric.fasl" ea)
  (load-fasl "CLOS/slot-definition-readers-defgeneric.fasl" ea)
  (load-fasl "CLOS/slot-definition-writers-defgeneric.fasl" ea)
  (load-fasl "CLOS/slot-definition-location-defgeneric.fasl" ea)
  (load-fasl "CLOS/setf-slot-definition-location-defgeneric.fasl" ea)
  (load-fasl "CLOS/variant-signature-defgeneric.fasl" ea)
  (load-fasl "CLOS/template-defgeneric.fasl" ea)
  (load-fasl "Package-and-symbol/symbol-name-defgeneric.fasl" ea)
  (load-fasl "Package-and-symbol/symbol-package-defgeneric.fasl" ea)
  (load-fasl "Compiler/Code-object/generic-functions.fasl" ea))

(defun define-accessor-generic-functions (ea eb ec)
  (sicl-boot:enable-defgeneric ea eb ec)
  (load-fasl "CLOS/invalidate-discriminating-function.fasl" eb)
  (enable-generic-function-initialization eb)
  (load-accessor-defgenerics ec))
