(cl:in-package #:sicl-boot-phase-5)

(defun boot (boot)
  (format *trace-output* "Start of phase 5~%")
  (with-accessors ((e4 sicl-boot:e4)
                   (e5 sicl-boot:e5))
      boot
    (change-class e5 'environment)
    (import-function-from-host 'cons e5)
    (enable-class-finalization boot)
    (finalize-all-classes boot)
    (enable-defmethod boot)
    (enable-allocate-instance e4)
    (enable-object-initialization boot)
    (enable-method-combinations boot)
    (enable-generic-function-invocation boot)
    (enable-defgeneric boot)
    (define-accessor-generic-functions boot)
    (enable-class-initialization boot)
    (create-mop-classes boot)))
