(cl:in-package #:sicl-boot-phase-5)

(defun define-class-of (e5)
  (setf (sicl-genv:fdefinition 'class-of e5)
        (lambda (object)
          (let ((result (cond ((typep object 'sicl-boot::header)
                               (slot-value object 'sicl-boot::%class))
                              ((consp object)
                               (sicl-genv:find-class 'cons e5))
                              ((null object)
                               (sicl-genv:find-class 'null e5))
                              ((symbolp object)
                               (sicl-genv:find-class 'symbol e5))
                              ((integerp object)
                               (sicl-genv:find-class 'fixnum e5))
                              ((streamp object)
                               (sicl-genv:find-class 't e5))
                              (t
                               (class-of object)))))
            result))))
