(cl:in-package #:sicl-boot-phase-5)

(defun enable-object-initialization (boot)
  (with-accessors ((e4 sicl-boot:e4)
                   (e5 sicl-boot:e5))
      boot
    (setf (sicl-genv:special-variable 'sicl-clos:+unbound-slot-value+ e4 t)
          10000000)
    (load-fasl "CLOS/slot-bound-using-index.fasl" e4)
    (load-fasl "CLOS/standard-instance-access.fasl" e4)
    (load-fasl "CLOS/slot-value-etc-support.fasl" e4)
    (load-fasl "CLOS/instance-slots-offset-defconstant.fasl" e4)
    (sicl-boot:with-straddled-function-definitions
        ((sicl-clos::shared-initialize-default-using-class)
         e5)
      (load-fasl "CLOS/shared-initialize-support.fasl" e4))
    (load-fasl "CLOS/shared-initialize-defgenerics.fasl" e5)
    (load-fasl "CLOS/shared-initialize-defmethods.fasl" e5)
    (load-fasl "CLOS/initialize-instance-support.fasl" e5)
    (load-fasl "CLOS/initialize-instance-defgenerics.fasl" e5)
    (load-fasl "CLOS/initialize-instance-defmethods.fasl" e5)
    (sicl-boot:define-make-instance e4 e5)))
