(cl:in-package #:sicl-boot-phase-0)

;;; Eclector defines macros that are generated by the backquote
;;; facility.  These macros must exist in the global environment
;;; so that they can be expanded by the compiler.

(defun define-backquote-macros (environment)
  (setf (sicl-genv:fdefinition 'eclector.reader::expand environment)
        (fdefinition 'eclector.reader::transform))
  (setf (sicl-genv:macro-function 'eclector.reader::quasiquote environment)
        (macro-function 'eclector.reader::quasiquote)))
